services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avaliacoes
    ports:
      - '5432:5432'
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
